---
# tasks file for vector-role
- name: Create vector work directory
  ansible.builtin.file:
    path: "{{ vector_workdir }}"
    state: directory
    mode: "0755"

- name: Get Vector distrib
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vector_os_arch }}-unknown-linux-gnu.tar.gz
    dest: "{{ vector_workdir }}/vector-{{ vector_version }}-{{ vector_os_arch }}-unknown-linux-gnu.tar.gz"
    mode: "0644"

- name: Unzip Vector archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ vector_workdir }}/vector-{{ vector_version }}-{{ vector_os_arch }}-unknown-linux-gnu.tar.gz"
    dest: "{{ vector_workdir }}"
